version: '3.8'
services:
  postgres:
    image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    restart: always
    build:
        context: ./nginx
        dockerfile: Dockerfile
    ports:
        - "80:80"
    depends_on:
        - nestjs  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf   
volumes:
  postgres_data:

